### PR TITLE
fix-4

### LINKED ISSUE #4: Schemas to break the tool
Hey @Skn0tt, nice tool - happy to see something like this from our community at Prisma!

If you see some `FUNCTION_INVOCATION_FAILED` in your server/function logs, that would be me trying out some of our Prisma internal testing schemas. I thought I might share them with you.

Here is one of our _monsters_:

[bench.schema.prisma.txt](https://github.com/Skn0tt/prisma-erd/files/6350893/bench.schema.prisma.txt)

This is a pretty simple. industry standard one:

```
model Album {
  AlbumId  Int     @id @default(autoincrement())
  Title    String  @db.VarChar(160)
  ArtistId Int
  Artist   Artist  @relation(fields: [ArtistId], references: [ArtistId])
  Track    Track[]

  @@index([ArtistId], name: "IFK_AlbumArtistId")
}

model Artist {
  ArtistId Int     @id @default(autoincrement())
  Name     String? @db.VarChar(120)
  Album    Album[]
}

model Customer {
  CustomerId   Int       @id @default(autoincrement())
  FirstName    String    @db.VarChar(40)
  LastName     String    @db.VarChar(20)
  Company      String?   @db.VarChar(80)
  Address      String?   @db.VarChar(70)
  City         String?   @db.VarChar(40)
  State        String?   @db.VarChar(40)
  Country      String?   @db.VarChar(40)
  PostalCode   String?   @db.VarChar(10)
  Phone        String?   @db.VarChar(24)
  Fax          String?   @db.VarChar(24)
  Email        String    @db.VarChar(60)
  SupportRepId Int?
  Employee     Employee? @relation(fields: [SupportRepId], references: [EmployeeId])
  Invoice      Invoice[]

  @@index([SupportRepId], name: "IFK_CustomerSupportRepId")
}

model Employee {
  EmployeeId     Int        @id @default(autoincrement())
  LastName       String     @db.VarChar(20)
  FirstName      String     @db.VarChar(20)
  Title          String?    @db.VarChar(30)
  ReportsTo      Int?
  BirthDate      DateTime?  @db.DateTime(0)
  HireDate       DateTime?  @db.DateTime(0)
  Address        String?    @db.VarChar(70)
  City           String?    @db.VarChar(40)
  State          String?    @db.VarChar(40)
  Country        String?    @db.VarChar(40)
  PostalCode     String?    @db.VarChar(10)
  Phone          String?    @db.VarChar(24)
  Fax            String?    @db.VarChar(24)
  Email          String?    @db.VarChar(60)
  Employee       Employee?  @relation("EmployeeToEmployee_ReportsTo", fields: [ReportsTo], references: [EmployeeId])
  Customer       Customer[]
  other_Employee Employee[] @relation("EmployeeToEmployee_ReportsTo")

  @@index([ReportsTo], name: "IFK_EmployeeReportsTo")
}

model Genre {
  GenreId Int     @id @default(autoincrement())
  Name    String? @db.VarChar(120)
  Track   Track[]
}

model Invoice {
  InvoiceId         Int           @id @default(autoincrement())
  CustomerId        Int
  InvoiceDate       DateTime      @db.DateTime(0)
  BillingAddress    String?       @db.VarChar(70)
  BillingCity       String?       @db.VarChar(40)
  BillingState      String?       @db.VarChar(40)
  BillingCountry    String?       @db.VarChar(40)
  BillingPostalCode String?       @db.VarChar(10)
  Total             Decimal       @db.Decimal(10, 2)
  Customer          Customer      @relation(fields: [CustomerId], references: [CustomerId])
  InvoiceLine       InvoiceLine[]

  @@index([CustomerId], name: "IFK_InvoiceCustomerId")
}

model InvoiceLine {
  InvoiceLineId Int     @id @default(autoincrement())
  InvoiceId     Int
  TrackId       Int
  UnitPrice     Decimal @db.Decimal(10, 2)
  Quantity      Int
  Invoice       Invoice @relation(fields: [InvoiceId], references: [InvoiceId])
  Track         Track   @relation(fields: [TrackId], references: [TrackId])

  @@index([InvoiceId], name: "IFK_InvoiceLineInvoiceId")
  @@index([TrackId], name: "IFK_InvoiceLineTrackId")
}

model MediaType {
  MediaTypeId Int     @id @default(autoincrement())
  Name        String? @db.VarChar(120)
  Track       Track[]
}

model Playlist {
  PlaylistId    Int             @id @default(autoincrement())
  Name          String?         @db.VarChar(120)
  PlaylistTrack PlaylistTrack[]
}

model PlaylistTrack {
  PlaylistId Int
  TrackId    Int
  Playlist   Playlist @relation(fields: [PlaylistId], references: [PlaylistId])
  Track      Track    @relation(fields: [TrackId], references: [TrackId])

  @@id([PlaylistId, TrackId])
  @@index([TrackId], name: "IFK_PlaylistTrackTrackId")
}

model Track {
  TrackId       Int             @id @default(autoincrement())
  Name          String          @db.VarChar(200)
  AlbumId       Int?
  MediaTypeId   Int
  GenreId       Int?
  Composer      String?         @db.VarChar(220)
  Milliseconds  Int
  Bytes         Int?
  UnitPrice     Decimal         @db.Decimal(10, 2)
  Album         Album?          @relation(fields: [AlbumId], references: [AlbumId])
  Genre         Genre?          @relation(fields: [GenreId], references: [GenreId])
  MediaType     MediaType       @relation(fields: [MediaTypeId], references: [MediaTypeId])
  InvoiceLine   InvoiceLine[]
  PlaylistTrack PlaylistTrack[]

  @@index([AlbumId], name: "IFK_TrackAlbumId")
  @@index([GenreId], name: "IFK_TrackGenreId")
  @@index([MediaTypeId], name: "IFK_TrackMediaTypeId")
}
```

Let me know if you need more, both huge or small, to test specific things - happy to help out here.

### PR DESCRIPTION
**Pull request by Skn0tt**
Closes #4

### CODE REVIEW

**Comment by Skn0tt** [comment]
The second example in #4 was fixed by updating to a current Prisma version (27c7be1). 2636041 makes it so that DMML parsing errors are show to users. For the *monster* schema (it is indeed pretty masochistic), it now shows `error: The index name `ICO` is declared multiple times. With the current connector index names have to be globally unique.`. Any idea what that's caused by?

**Comment by janpio** [comment]
Hm, I think that datamodel is from a mysql database (which we found on the internet by the way, part of some academic work around database models). I removed the `datasource` block, to follow your example, so you are probably missing that information in the script and assuming a default of `postgresql` or `sqlite` maybe?

**Comment by Skn0tt** [comment]
I see. I use Prisma's own query-engine to parse the DMML, so it likely failed b/c that defaulted to non-MySQL. I've updated the example to show that the datasource is required.

**Comment by Skn0tt** [comment]
Can you confirm that this PR now fixes all of the issues mentioned in #5?

**Comment by Skn0tt** [comment]
Interesting! Vercel functions don't seem to support optional chaining 🧐

**Pull request merged**
